### ISSUE TITLE
Replace is not working

### ISSUE THREAD

**Issue by deepakshrma** [ktonon/react-native-port-patcher#1]
Created new Project
react-native-cli: 2.0.1
react-native: 0.52.0

install--
npm i -g react-native-port-patcher

Command run to replace:
react-native-port-patcher --new-port 8888

Command run: 
react-native run-ios

**Comment by tangkunyin** [comment]
@deepakshrma The plugin work fine for me.

First, add plugin to package.json file like this

```
"devDependencies": {
        "babel-jest": "22.1.0",
        "babel-preset-react-native": "4.0.0",
        "jest": "22.1.1",
        "react-test-renderer": "16.2.0",
        "babel-plugin-transform-decorators-legacy": "^1.3.4",
        "babel-eslint": "7.1.1",
        "eslint": "3.17.1",
        "eslint-config-airbnb": "14.1.0",
        "eslint-plugin-import": "2.2.0",
        "eslint-plugin-jsx-a11y": "4.0.0",
        "eslint-plugin-react": "6.10.0",
        "fetch-polyfill": "^0.8.2",
        "form-urlencoded": "^0.1.5",
        "url": "^0.11.0",
        "react-native-port-patcher": "^1.0.2"
    }
```

Second, run yarn install

![image](https://user-images.githubusercontent.com/4197468/35094969-eb4077cc-fc81-11e7-88db-18adc40e31cf.png)


Then open your XCode and rebuild app. It works.

Thanks author @ktonon

**Comment by tangkunyin** [comment]
don't forget put `"postinstall": "react-native-port-patcher --new-port 9090"` in you scripts scope

**Comment by ktonon** [comment]
@deepakshrma does the solution posted by @tangkunyin help?

**Comment by deepakshrma** [comment]
@tangkunyin : I will try. For the time, I created very small regex script for now. Thanks.
